{"name": "test_login_with_incorrect_creds", "status": "passed", "description": "\n        Check log in with invalid credentials.\n        ", "steps": [{"name": "Enter username: qwerty", "status": "passed", "start": 1688990066659, "stop": 1688990067130}, {"name": "Enter password: 123", "status": "passed", "start": 1688990067130, "stop": 1688990067321}, {"name": "Click on login button", "status": "passed", "start": 1688990067321, "stop": 1688990067470}, {"name": "Check the alert contains \"Invalid credentials\"", "status": "passed", "start": 1688990067470, "stop": 1688990068283}], "attachments": [{"name": "log", "source": "8ebd91df-da30-4632-b856-675b28493b4c-attachment.txt", "type": "text/plain"}], "start": 1688990066658, "stop": 1688990068284, "uuid": "109821a9-0676-4cb3-b97f-5a13d608124a", "historyId": "348c71756a907aa3d75513fd783704aa", "testCaseId": "348c71756a907aa3d75513fd783704aa", "fullName": "tests.test_login.TestLogin#test_login_with_incorrect_creds", "labels": [{"name": "story", "value": "Log in with invalid credentials"}, {"name": "feature", "value": "Log in"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-HVDQGLK"}, {"name": "thread", "value": "14436-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}